### ISSUE TITLE
what am i doing wrong?

### ISSUE THREAD

**Issue by Sean1140** [joshvillbrandt/goprohero#19]
this is the error i am recieving.  Is this .py just outdated? loosing my mind here

> Traceback (most recent call last):
>   File "/usr/bin/goproctl", line 23, in <module>
>     network = Wireless(args.interface)
> AttributeError: 'Namespace' object has no attribute 'interface'

**Comment by agamirzov** [comment]
If someone is still interested.

This bug is fixed by @samdnic but _pip_ has an older buggy version, so be careful. To have CLI working, clone the repository and instal via _setup.py_ and then use like:

$ _goproctl ssid password param value --interface interface_

Name of the network interface can be obtained with _ifconfig_.
